Style: Hamburger Menu
Lambda-School-Labs/Labs25-SaverLife-TeamC-fe pull request #5
Opened 2020-08-11 22:20 UTC by chelsabeth

Styled the homepage hamburger menu with all our components for our user flow

<Trello> 
Dashboard/Home: https://trello.com/c/A0I4POG8

2020-08-11 22:32 UTC, vtopham requested changes
There are two typos that i'd love to change before this gets merged!

2020-08-11 22:32 UTC, vtopham commented on src/index.css
> +.content-conatiner {
this has a typo, can we correct this? :)

2020-08-11 22:32 UTC, vtopham commented on src/components/pages/Home/RenderHomePage.js
> +      <div className="content-conatiner">
this one is also misspelled- they're both spelled the same way but it would be good to have them correct for future use.

2020-08-12 15:51 UTC, locbgiang approved these changes

2020-08-12 15:52 UTC, imriven approved these changes
Looks like the needed corrections were made. Thanks for the extra vigilance

2020-08-12 15:55 UTC, vtopham approved these changes

2020-08-12 15:56 UTC, merged